# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='categorys',
            new_name='categories',
        ),
    ]
