# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0003_auto_20161202_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='image',
            field=models.ImageField(default=None, upload_to='organisation/image'),
        ),
    ]
