# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0007_auto_20161203_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
