# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0009_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='regions',
            field=models.ManyToManyField(to='charitymatch.Region'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='countries',
            field=models.ManyToManyField(to='charitymatch.Country'),
        ),
    ]
