# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0010_auto_20161203_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, null=True, upload_to='charitymatch/static/charitymatch/subcategories/image')),
                ('image_text', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='charitymatch/static/charitymatch/categories/image'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='categories',
            field=models.ManyToManyField(to='charitymatch.SubCategory'),
        ),
        migrations.DeleteModel(
            name='Category_type',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charitymatch.Category'),
        ),
    ]
