# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0011_auto_20161203_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='charitymatch/static/charitymatch/categories/image'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='charitymatch/static/charitymatch/organisations/image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='charitymatch/static/charitymatch/subcategories/image'),
        ),
    ]
