# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitymatch', '0014_auto_20161203_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='methods',
            field=models.ManyToManyField(null=True, to='charitymatch.Method'),
        ),
    ]
